current_pipeline: complex
number_of_seeds: 5
max_combined_seq_length: 7000
template_file: input_fasta/alphafold3_input_template_protein_complexes.json

fixed_proteins:
- PxdA
- AN4585
- AN3602
- AN4965

input_fasta: examples/complex/PxdA.fasta
output_folder: output_protein_complex/PxdA