current_pipeline: complex
number_of_seeds: 5
max_combined_seq_length: 7000
process_count: 6

fixed_proteins:
- PxdA
- AN4585
- AN3602
- AN4965

input_fasta: examples/complex/PxdA.fasta
output_folder: output_protein_complex/PxdA