current_pipeline: pulldown
number_of_seeds: 2
max_combined_seq_length: 3600
process_count: 6

bait_filename: input_fasta/bait_LRRK2_ROC_COR.fasta
superfolder_to_fasta_and_folder:
  GAP:
    - [input_fasta/uniprotkb_GTPase_Activating_Protein_AND_2024_11_09_0AA_600AA.fasta, GAP_0AA_600AA_AF3_SCREEN]
    - [input_fasta/uniprotkb_GTPase_Activating_Protein_AND_2024_11_09_600AA_1000AA.fasta, GAP_600AA_1000AA_AF3_SCREEN]
    - [input_fasta/uniprotkb_GTPase_Activating_Protein_AND_2024_11_09_1000AA_1500AA.fasta, GAP_1000AA_1500AA_AF3_SCREEN]
    - [input_fasta/uniprotkb_GTPase_Activating_Protein_AND_2024_11_09_1500AA_2000AA.fasta, GAP_1500AA_2000AA_AF3_SCREEN]
  GEF:
    - [input_fasta/uniprotkb_Guanine_Nucleotide_Exchange_F_2024_11_08_0AA_600AA.fasta, GEF_0AA_600AA_AF3_SCREEN]
    - [input_fasta/uniprotkb_Guanine_Nucleotide_Exchange_F_2024_11_08_600AA_1000AA.fasta, GEF_600AA_1000AA_AF3_SCREEN]
    - [input_fasta/uniprotkb_Guanine_Nucleotide_Exchange_F_2024_11_08_1000AA_1500AA.fasta, GEF_1000AA_1500AA_AF3_SCREEN]
    - [input_fasta/uniprotkb_Guanine_Nucleotide_Exchange_F_2024_11_08_1500AA_2000AA.fasta, GEF_1500AA_2000AA_AF3_SCREEN]

plddt_sliding_window: 11
all_plddt_windows: [-1, 11, 25]
prediction_threshold_metric: ipTM
prediction_threshold_metric_value: 0.4

min_contacts_thresholds: [1, 20, 80]
domains_to_residues:
  ROC:
    - 1 # 1317 - 1316
    - 205 # 1521 - 1316
  "COR-A":
    - 206 # 1522 - 1316
    - 355 # 1671 - 1316
  "COR-B":
    - 356 # 1672 - 1316
    - 557 # 1873 - 1316

clashes_model: "LRRK2_RCKW.pdb"
max_clashes_threshold: 1000
