bait_filename: input_fasta/bait_LRRK2_ROC_COR.fasta
template_file: input_fasta/alphafold3_input_template_roc_cor.json
number_of_seeds: 2

superfolder_to_fasta_and_folder:
  GAP:
    - [input_fasta/uniprotkb_GTPase_Activating_Protein_AND_2024_11_09_0AA_600AA.fasta, GAP_0AA_600AA_AF3_SCREEN]
    - [input_fasta/uniprotkb_GTPase_Activating_Protein_AND_2024_11_09_600AA_1000AA.fasta, GAP_600AA_1000AA_AF3_SCREEN]
    - [input_fasta/uniprotkb_GTPase_Activating_Protein_AND_2024_11_09_1000AA_1500AA.fasta, GAP_1000AA_1500AA_AF3_SCREEN]
    - [input_fasta/uniprotkb_GTPase_Activating_Protein_AND_2024_11_09_1500AA_2000AA.fasta, GAP_1500AA_2000AA_AF3_SCREEN]
  GEF:
    - [input_fasta/uniprotkb_Guanine_Nucleotide_Exchange_F_2024_11_08_0AA_600AA.fasta, GEF_0AA_600AA_AF3_SCREEN]
    - [input_fasta/uniprotkb_Guanine_Nucleotide_Exchange_F_2024_11_08_600AA_1000AA.fasta, GEF_600AA_1000AA_AF3_SCREEN]
    - [input_fasta/uniprotkb_Guanine_Nucleotide_Exchange_F_2024_11_08_1000AA_1500AA.fasta, GEF_1000AA_1500AA_AF3_SCREEN]
    - [input_fasta/uniprotkb_Guanine_Nucleotide_Exchange_F_2024_11_08_1500AA_2000AA.fasta, GEF_1500AA_2000AA_AF3_SCREEN]

domains_to_residues:
  ROC:
    - 1 # 1317 - 1316
    - 205 # 1521 - 1316
  "COR-A":
    - 206 # 1522 - 1316
    - 355 # 1671 - 1316
  "COR-B":
    - 356 # 1672 - 1316
    - 557 # 1873 - 1316
